// SimConnect event names for MSFS
export const events = {
  // Autopilot
  AP_MASTER: 'AP_MASTER',
  AP_ALT_HOLD: 'AP_ALT_HOLD',
  AP_HEADING_HOLD: 'AP_HEADING_HOLD',
  AP_AIRSPEED_HOLD: 'AP_AIRSPEED_HOLD',
  AP_VS_HOLD: 'AP_VS_HOLD',
  AP_NAV1_HOLD: 'AP_NAV1_HOLD',
  AP_APR_HOLD: 'AP_APR_HOLD',

  // Throttle
  THROTTLE_FULL: 'THROTTLE_FULL',
  THROTTLE_CUT: 'THROTTLE_CUT',
  THROTTLE_INCR: 'THROTTLE_INCR',
  THROTTLE_DECR: 'THROTTLE_DECR',
  THROTTLE_SET: 'THROTTLE_SET',

  // Flaps
  FLAPS_UP: 'FLAPS_UP',
  FLAPS_DOWN: 'FLAPS_DOWN',
  FLAPS_INCR: 'FLAPS_INCR',
  FLAPS_DECR: 'FLAPS_DECR',
  FLAPS_SET: 'FLAPS_SET',

  // Landing Gear
  GEAR_TOGGLE: 'GEAR_TOGGLE',
  GEAR_UP: 'GEAR_UP',
  GEAR_DOWN: 'GEAR_DOWN',

  // Brakes
  BRAKES: 'BRAKES',
  PARKING_BRAKES: 'PARKING_BRAKES',

  // Camera
  CAMERA_ACTION: 'CAMERA_ACTION',

  // Freeze
  FREEZE_LATITUDE_LONGITUDE_SET: 'FREEZE_LATITUDE_LONGITUDE_SET',
  FREEZE_ALTITUDE_SET: 'FREEZE_ALTITUDE_SET',
  FREEZE_ATTITUDE_SET: 'FREEZE_ATTITUDE_SET',

  // Lights
  TOGGLE_MASTER_BATTERY: 'TOGGLE_MASTER_BATTERY',
  LANDING_LIGHTS_TOGGLE: 'LANDING_LIGHTS_TOGGLE',
  STROBES_TOGGLE: 'STROBES_TOGGLE',
  TOGGLE_NAV_LIGHTS: 'TOGGLE_NAV_LIGHTS',
} as const;

export type EventName = typeof events[keyof typeof events];
