// Auto-generated from sim-registry.txt – do not edit manually

export const units = {
  METER: 'meter',
  METER_SCALER_256: 'meter scaler 256',
  MILLIMETER: 'millimeter',
  CENTIMETER: 'centimeter',
  KILOMETER: 'kilometer',
  NAUTICAL_MILE: 'nautical mile',
  DECINMILE: 'decinmile',
  INCH: 'inch',
  FOOT: 'foot',
  YARD: 'yard',
  DECIMILE: 'decimile',
  MILE: 'mile',
  SQUARE_INCH: 'square inch',
  SQUARE_FEET: 'square feet',
  SQUARE_YARD: 'square yard',
  SQUARE_MILE: 'square mile',
  SQUARE_MILLIMETER: 'square millimeter',
  SQUARE_CENTIMETER: 'square centimeter',
  SQUARE_METER: 'square meter',
  SQUARE_KILOMETER: 'square kilometer',
  CUBIC_INCH: 'cubic inch',
  CUBIC_FOOT: 'cubic foot',
  CUBIC_YARD: 'cubic yard',
  CUBIC_MILE: 'cubic mile',
  CUBIC_MILLIMETER: 'cubic millimeter',
  CUBIC_CENTIMETER: 'cubic centimeter',
  CUBIC_METER: 'cubic meter',
  CUBIC_KILOMETER: 'cubic kilometer',
  LITER: 'liter',
  GALLON: 'gallon',
  QUART: 'quart',
  FS7_OIL_QUANTITY: 'fs7 oil quantity',
  KELVIN: 'kelvin',
  RANKINE: 'rankine',
  FARENHEIT: 'farenheit',
  CELSIUS: 'celsius',
  CELSIUS_FS7_EGT: 'celsius fs7 egt',
  CELSIUS_FS7_OIL_TEMP: 'celsius fs7 oil temp',
  CELSIUS_SCALER_1_256: 'celsius scaler 1/256',
  CELSIUS_SCALER_256: 'celsius scaler 256',
  CELSIUS_SCALER_16K: 'celsius scaler 16k',
  RADIAN: 'radian',
  ROUND: 'round',
  DEGREE: 'degree',
  GRAD: 'grad',
  ANGL16: 'angl16',
  ANGL32: 'angl32',
  DEGREE_LATITUDE: 'degree latitude',
  DEGREE_LONGITUDE: 'degree longitude',
  METER_LATITUDE: 'meter latitude',
  RADIAN_PER_SECOND: 'radian per second',
  REVOLUTION_PER_MINUTE: 'revolution per minute',
  RPM_1_OVER_16K: 'rpm 1 over 16k',
  MINUTE_PER_ROUND: 'minute per round',
  NICE_MINUTE_PER_ROUND: 'nice minute per round',
  DEGREE_PER_SECOND: 'degree per second',
  DEGREE_PER_SECOND_ANG16: 'degree per second ang16',
  RADIAN_PER_SECOND_SQUARED: 'radian per second squared',
  DEGREE_PER_SECOND_SQUARED: 'degree per second squared',
  METER_PER_SECOND: 'meter per second',
  METER_PER_SECOND_SCALER_256: 'meter per second scaler 256',
  METER_PER_MINUTE: 'meter per minute',
  KILOMETER_HOUR: 'kilometer/hour',
  FEET_SECOND: 'feet/second',
  FEET_MINUTE: 'feet/minute',
  MILE_PER_HOUR: 'mile per hour',
  KNOT: 'knot',
  KNOT_SCALER_128: 'knot scaler 128',
  MACH: 'mach',
  MACH_3D2_OVER_64K: 'mach 3d2 over 64k',
  METER_PER_SECOND_SQUARED: 'meter per second squared',
  FEET_PER_SECOND_SQUARED: 'feet per second squared',
  GFORCE: 'Gforce',
  G_FORCE_624_SCALED: 'G Force 624 scaled',
  SECOND: 'second',
  MINUTE: 'minute',
  HOUR: 'hour',
  DAY: 'day',
  HOUR_OVER_10: 'hour over 10',
  YEAR: 'year',
  WATT: 'Watt',
  FT_LB_PER_SECOND: 'ft lb per second',
  METER_CUBED_PER_SECOND: 'meter cubed per second',
  LITER_PER_HOUR: 'liter per hour',
  GALLON_PER_HOUR: 'gallon per hour',
  KILOGRAM: 'kilogram',
  POUND: 'pound',
  POUND_SCALER_256: 'pound scaler 256',
  SLUG: 'slug',
  KILOGRAM_PER_SECOND: 'kilogram per second',
  POUND_PER_HOUR: 'pound per hour',
  AMPERE: 'ampere',
  FS7_CHARGING_AMPS: 'fs7 charging amps',
  VOLT: 'volt',
  HERTZ: 'Hertz',
  KILOHERTZ: 'Kilohertz',
  MEGAHERTZ: 'Megahertz',
  FREQUENCY_BCD16: 'Frequency BCD16',
  FREQUENCY_BCD32: 'Frequency BCD32',
  FREQUENCY_ADF_BCD32: 'Frequency ADF BCD32',
  KILOGRAM_PER_CUBIC_METER: 'kilogram per cubic meter',
  SLUG_PER_CUBIC_FEET: 'Slug per cubic feet',
  POUND_PER_GALLON: 'pound per gallon',
  PASCAL: 'pascal',
  KILOPASCAL: 'kilopascal',
  MILLIMETER_OF_MERCURY: 'millimeter of mercury',
  CENTIMETER_OF_MERCURY: 'centimeter of mercury',
  INCH_OF_MERCURY: 'inch of mercury',
  INHG_64_OVER_64K: 'inHg 64 over 64k',
  MILLIMETER_OF_WATER: 'millimeter of water',
  NEWTON_PER_SQUARE_METER: 'Newton per square meter',
  KILOGRAM_FORCE_PER_SQUARE_CENTIMETER: 'kilogram force per square centimeter',
  KILOGRAM_METER_SQUARED: 'kilogram meter squared',
  ATMOSPHERE: 'atmosphere',
  BAR: 'bar',
  MILLIBAR: 'millibar',
  MILLIBAR_SCALER_16: 'millibar scaler 16',
  POUND_FORCE_PER_SQUARE_INCH: 'pound-force per square inch',
  PSI_SCALER_16K: 'psi scaler 16k',
  PSI_4_OVER_16K: 'psi 4 over 16k',
  PSI_FS7_OIL_PRESSURE: 'psi fs7 oil pressure',
  POUND_FORCE_PER_SQUARE_FOOT: 'pound-force per square foot',
  PSF_SCALER_16K: 'psf scaler 16k',
  SLUG_FEET_SQUARED: 'slug feet squared',
  BOOST_CMHG: 'boost cmHg',
  BOOST_INHG: 'boost inHg',
  BOOST_PSI: 'boost psi',
  NEWTON_METER: 'Newton meter',
  FOOT_POUND: 'foot-pound',
  LBF_FEET: 'lbf-feet',
  KILOGRAM_METER: 'kilogram meter',
  POUNDAL_FEET: 'poundal feet',
  FRACTIONALLATLONDIGITS: 'FractionalLatLonDigits',
  PART: 'part',
  HALF: 'half',
  THIRD: 'third',
  PERCENT: 'percent',
  PERCENT_OVER_100: 'percent over 100',
  PERCENT_SCALER_16K: 'percent scaler 16k',
  PERCENT_SCALER_32K: 'percent scaler 32k',
  PERCENT_SCALER_2POW23: 'percent scaler 2pow23',
  BEL: 'bel',
  DECIBEL: 'decibel',
  MORE_THAN_A_HALF: 'more_than_a_half',
  TIMES: 'times',
  RATIO: 'ratio',
  NUMBER: 'number',
  SCALER: 'scaler',
  POSITION: 'position',
  ENUM: 'Enum',
  BOOL: 'Bool',
  BCO16: 'Bco16',
  MASK: 'mask',
  FLAGS: 'flags',
  STRING: 'string',
  PER_RADIAN: 'per radian',
  PER_DEGREE: 'per degree',
  KEYFRAME: 'keyframe',
  XYZ: 'XYZ',
  PBH: 'PBH',
  LATLONALTPBH: 'latlonaltpbh',
  LATLONALT: 'latlonalt',
  PID_STRUCT: 'PID_STRUCT',
  POILIST: 'POIList',
  GLASSCOCKPITSETTINGS: 'GlassCockpitSettings',
  FUELLEVELS: 'FuelLevels',
} as const;

export type UnitsKey = typeof units[keyof typeof units];
