// SimConnect variable names for MSFS
export const vars = {
  // Airspeed
  AIRSPEED_INDICATED: 'AIRSPEED INDICATED',
  AIRSPEED_TRUE: 'AIRSPEED TRUE',
  AIRSPEED_MACH: 'AIRSPEED MACH',
  VERTICAL_SPEED: 'VERTICAL SPEED',

  // Altitude & Position
  ALTITUDE: 'PLANE ALTITUDE',
  ALTITUDE_ABOVE_GROUND: 'PLANE ALT ABOVE GROUND',
  LATITUDE: 'PLANE LATITUDE',
  LONGITUDE: 'PLANE LONGITUDE',

  // Attitude
  PITCH_ATTITUDE: 'PLANE PITCH DEGREES',
  BANK_ATTITUDE: 'PLANE BANK DEGREES',
  HEADING_MAGNETIC: 'PLANE HEADING DEGREES MAGNETIC',
  HEADING_TRUE: 'PLANE HEADING DEGREES TRUE',

  // Engine
  ENGINE_RPM: 'GENERAL ENG RPM:1',
  THROTTLE_PCT: 'GENERAL ENG THROTTLE LEVER POSITION:1',
  FUEL_TOTAL_PCT: 'FUEL TOTAL QUANTITY WEIGHT',

  // Navigation
  GPS_GROUND_SPEED: 'GPS GROUND SPEED',
  GPS_GROUND_TRACK: 'GPS GROUND MAGNETIC TRACK',

  // Autopilot
  AUTOPILOT_MASTER: 'AUTOPILOT MASTER',
  AUTOPILOT_ALTITUDE_LOCK_VAR: 'AUTOPILOT ALTITUDE LOCK VAR',
  AUTOPILOT_HEADING_LOCK_DIR: 'AUTOPILOT HEADING LOCK DIR',

  // Misc
  SIM_ON_GROUND: 'SIM ON GROUND',
  FLAPS_HANDLE_INDEX: 'FLAPS HANDLE INDEX',
  GEAR_HANDLE_POSITION: 'GEAR HANDLE POSITION',
  BRAKE_PARKING_INDICATOR: 'BRAKE PARKING INDICATOR',
} as const;

export type VarName = typeof vars[keyof typeof vars];
